name: Rustjs CI
on: [push]

jobs:
  test-clippy-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v4
      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: test
        run: nix develop -c cargo test

      - name: clippy
        run: nix develop -c cargo clippy --all-targets --all-features -- -D clippy::all

      - name: fmt
        run: nix develop -c cargo fmt --all -- --check